# H2 Console
spring:
  h2:
    console:
      enabled: true
      path: /h2

# DATASOURCE
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password:

# JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

# Server
server:
  servlet:
    context-path=: /analisecredito